# Generated by Django 4.2 on 2024-02-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('key', models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('WELCOME', 'WELCOME')], max_length=255, null=True)),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='interface',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('WELCOME', 'WELCOME')], max_length=255),
        ),
    ]
