# Generated by Django 4.2 on 2024-02-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notificationmessage_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notification.notificationtemplate'),
        ),
    ]
