# Generated by Django 4.2 on 2024-02-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notificationmessage_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTranslate',
            new_name='NotificationMessageTranslate',
        ),
    ]
