# Generated by Django 4.2 on 2024-02-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_notification_notificationsended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsended',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('error', 'error'), ('read', 'read'), ('deleted', 'deleted')], default='pending', max_length=255),
        ),
    ]
