# Generated by Django 4.2 on 2024-02-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationsended_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtemplatetranslate',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notificationtemplatetranslate',
            old_name='name',
            new_name='object',
        ),
    ]
